### ISSUE TITLE
what's this?

### ISSUE THREAD

**Issue by admonkey** [jessgusclark/gadget-material-icons#1]
not an issue per se, inasmuch as a request for documentation. what's the goal of this project? is it just a gadget for users to drop an icon on the page, so could be used just the same for other icons like font-awesome? I am curious because I was recently introduced to https://material.google.com/ and it's pretty, wow. Not sure how we're going to integrate these new design principles with OU, but seeing this repo I'm very intrigued with your approach.

**Comment by jessgusclark** [comment]
Hey Jeff, it is still in progress, I should have it completed by Monday or Tuesday and I'll provide "full" documentation thenish.

Our web authors really want the ability to add icons to their pages and our designer found the Material icons as one that she liked. So the original thought was to use snippets to place icons in but there are hundreds of icons so that would clutter up the snippet list. The other problem is that the WYSIWYG editor doesn't do well with empty divs, especially trying to place the cursor before or after them. So I figured a table transformation would be a "good" solution.

Well, tables suck, and although you can put your mouse before and after them, they are block elements so inline icons won't work. So, the gadget will place in a placeholder icon and then the XSL transformation will convert it to the icon on preview and publish. 

Yes, I think this could work with font-awesome as well. I don't think OUCampus would ever implement icons natively since they would be part of the design.  

Let me finish up early this week and then I'd be happy to chat about the logistics of the whole thing and then contributing if you are interested.

**Comment by jessgusclark** [comment]
I have finished up the last little bit of code and will post something over on the OU Forum in a little bit. I have beefed up the documentation and added an install via github pages. If you have time, please check it out! All feedback is welcomed!
